[package]
name = "broadcast-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

[dev-dependencies]
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.2"
proptest = "1"
